In [18]:
import numpy as np
import pandas as pd

In [4]:
a = np.arange(20)

In [6]:
#reshape(rows, columns)
a = a.reshape(5,4)

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
a.mean()

9.5

In [12]:
a.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [16]:
a[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [19]:
df = pd.read_csv(r'C:\Users\btam\Documents\Python_Folder\DAT-06-24\class material\Unit 2\data\titanic.csv')

In [20]:
pwd

'C:\\Users\\btam\\Documents\\Python_Folder\\Class_Notes'

In [21]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [23]:
df.shape

(891, 12)

In [24]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [28]:
df.mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [31]:
df[['Age','Name']][:10]

Age                                               Name
0  22.0                            Braund, Mr. Owen Harris
1  38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2  26.0                             Heikkinen, Miss. Laina
3  35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4  35.0                           Allen, Mr. William Henry
5   NaN                                   Moran, Mr. James
6  54.0                            McCarthy, Mr. Timothy J
7   2.0                     Palsson, Master. Gosta Leonard
8  27.0  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9  14.0                Nasser, Mrs. Nicholas (Adele Achem)

In [39]:
df.iloc[2:7,[3,4,6]]

Name     Sex  SibSp
2                        Heikkinen, Miss. Laina  female      0
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1
4                      Allen, Mr. William Henry    male      0
5                              Moran, Mr. James    male      0
6                       McCarthy, Mr. Timothy J    male      0

In [41]:
df.Age.mean()

29.69911764705882

In [42]:
df.Age > 25

0      False
1       True
2       True
3       True
4       True
5      False
6       True
7      False
8       True
9      False
10     False
11      True
12     False
13      True
14     False
15      True
16     False
17     False
18      True
19     False
20      True
21      True
22     False
23      True
24     False
25      True
26     False
27     False
28     False
29     False
       ...  
861    False
862     True
863    False
864    False
865     True
866     True
867     True
868    False
869    False
870     True
871     True
872     True
873     True
874     True
875    False
876    False
877    False
878    False
879     True
880    False
881     True
882    False
883     True
884    False
885     True
886     True
887    False
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

In [43]:
df[df.Age>25]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
8              9         1       3   
11            12         1       1   
13            14         0       3   
15            16         1       2   
18            19         0       3   
20            21         0       2   
21            22         1       2   
23            24         1       1   
25            26         1       3   
30            31         0       1   
33            34         0       2   
34            35         0       1   
35            36         0       1   
40            41         0       3   
41            42         0       2   
52            53         1       1   
53            54         1       2   
54            55         0       1   
57            58         0       3   
61            62         1       1   
62            63         0       1   
66            67         1       2   
69            70         0       3   
70            71         0       2   
73            74         0       3   
..           ...       ...     ...   
823          824         1       3   
829          830         1       1   
835          836         1       1   
838          839         1       3   
842          843         1       1   
843          844         0       3   
845          846         0       3   
847          848         0       3   
848          849         0       2   
851          852         0       3   
854          855         0       2   
856          857         1       1   
857          858         1       1   
860          861         0       3   
862          863         1       1   
865          866         1       2   
866          867         1       2   
867          868         0       1   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
879          880         1       1   
881          882         0       3   
883          884         0       2   
885          886         0       3   
886          887         0       2   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
20                                Fynney, Mr. Joseph J    male  35.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
30                            Uruchurtu, Don. Manuel E    male  40.0      0   
33                               Wheadon, Mr. Edward H    male  66.0      0   
34                             Meyer, Mr. Edgar Joseph    male  28.0      1   
35                      Holverson, Mr. Alexander Oskar    male  42.0      1   
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.0      1   
41   Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.0

In [44]:
df[df.Age > 30][df.Fare > 5]['Survived'][:30]

C:\Users\btam\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


1      1
3      1
4      0
6      0
11     1
13     0
15     1
18     0
20     0
21     1
25     1
30     0
33     0
35     0
40     0
52     1
54     0
61     1
62     0
70     0
74     1
85     1
92     0
94     0
96     0
98     1
99     0
103    0
104    0
108    0
Name: Survived, dtype: int64

In [50]:
df[(df.Age>25) & (df.Survived == 1) & (df.Fare >20)]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
11            12         1       1   
23            24         1       1   
25            26         1       3   
52            53         1       1   
53            54         1       2   
61            62         1       1   
74            75         1       3   
98            99         1       2   
133          134         1       2   
187          188         1       1   
194          195         1       1   
195          196         1       1   
209          210         1       1   
211          212         1       2   
215          216         1       1   
218          219         1       1   
224          225         1       1   
230          231         1       1   
248          249         1       1   
257          258         1       1   
258          259         1       1   
259          260         1       2   
268          269         1       1   
269          270         1       1   
275          276         1       1   
279          280         1       3   
290          291         1       1   
299          300         1       1   
..           ...       ...     ...   
690          691         1       1   
701          702         1       1   
707          708         1       1   
712          713         1       1   
716          717         1       1   
724          725         1       1   
726          727         1       2   
730          731         1       1   
737          738         1       1   
754          755         1       2   
759          760         1       1   
763          764         1       1   
765          766         1       1   
774          775         1       2   
779          780         1       1   
796          797         1       1   
801          802         1       2   
809          810         1       1   
820          821         1       1   
829          830         1       1   
835          836         1       1   
838          839         1       3   
842          843         1       1   
856          857         1       1   
857          858         1       1   
862          863         1       1   
871          872         1       1   
874          875         1       2   
879          880         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1   
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1   
61                                 Icard, Miss. Amelie  female  38.0      0   
74                                       Bing, Mr. Lee    male  32.0      0   
98                Doling, Mrs. John T (Ada Julia Bone)  female  34.0      0   
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0      1   
187      Romaine, Mr. Charles Hallace ("Mr C Rolmane")    male  45.0      0   
194          Brown, Mrs. James Joseph (Margaret Tobin)  female  44.0      0   
195                               Lurette, Miss. Elise  female  58.0      0   
209                                   Blank, Mr. Henry    male  40.0      0   
211                         Cameron, Miss. Clear Annie  female  35.0      0   
215                            Newell, Miss. Madeleine  female  31.0      1   
218                              Bazzani, Miss. Albina  female  32.0      0   
224                       Hoyt, Mr. Frederick Maxfield    male  38.0      1   
230       Harris, Mrs. Henry Birkhardt (Irene Wallach)  female  35.0